# -*- coding: utf-8 -*-
"""Mapa de Obras MOPC scrapeado

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6yJ9shEHL-LHmGFafVKdClDqrsfRu6A
"""

!pip install requests-html

from requests_html import HTMLSession
session = HTMLSession()
r = session.get('https://a.tiles.mapbox.com/v4/mopc.iobaeb6c/features.json?access_token=pk.eyJ1IjoibW9wYyIsImEiOiJKNFo3aktvIn0.tQGSxRugkpMUIcxUskZHgQ')
#r.text

import json
json_obras = json.loads(r.text)
#json_obras

obras = []
for obra in json_obras["features"]:
  row ={}
 
  properties = obra["properties"]
  geometry = obra["geometry"]

  
  row["ID"] = obra["id"]

  row["TITULO"] = properties["title"]
  row["DESCRIPCION"] = properties["description"]
  
  row["COORDENADAS"] = geometry["coordinates"]
  row["TIPO DE GEOMETRIA"] = geometry["type"]
  obras.append(row)
#obras

import pandas as pd

obras_formato = pd.DataFrame(obras)
obras_formato

obras_formato.to_csv("ObrasMOPC.csv")